### ISSUE TITLE
AttributeError: '<class 'praw.objects.Submission'>' has no attribute 'comments'

### ISSUE THREAD

**Issue by reikairen** [rhiever/reddit-analysis#57]
Anybody know how to fix? Has Reddit changed too much since this tools most recent release to be salvaged? Thank you.

C:\Windows\System32\reddit-analysis>word_freqs myusername /r/news
Analyzing /r/news
.Traceback (most recent call last):
  File "C:\Program Files\Python39\Scripts\word_freqs-script.py", line 33, in <module>
    sys.exit(load_entry_point('redditanalysis==1.0.5', 'console_scripts', 'word_freqs')())
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\redditanalysis\__init__.py", line 333, in main
    process_subreddit(subreddit=reddit.get_subreddit(target),
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\redditanalysis\__init__.py", line 294, in process_subreddit
    process_submission(submission=submission,
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\redditanalysis\__init__.py", line 256, in process_submission
    submission.replace_more_comments()
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\praw\objects.py", line 1301, in replace_more_comments
    more_comments = self._extract_more_comments(self.comments)
  File "C:\Users\myusername\AppData\Roaming\Python\Python39\site-packages\praw\objects.py", line 92, in __getattr__
    raise AttributeError(msg)
AttributeError: '<class 'praw.objects.Submission'>' has no attribute 'comments'

**Comment by veonua** [comment]
you have to use an old version of praw.
but it seems like it works very slow
